### ISSUE TITLE
Stand-alone tool?

### ISSUE THREAD

**Issue by gmierz** [russellu/eegfmripy#2]
Would this be something we would like? i.e. a tool we could invoke from bash/CLI that does not require MNE to be used.

If so, we could use python's `setuptools` tool, here's an example of what I am thinking: https://github.com/gmierz/coco-tools/blob/new_tool/setup.py

If we don't want anything like this, we can close this issue.

**Comment by russellu** [comment]
yes, this would definitely be useful. ideally, we would just input an EEG raw file and an FMRI raw file at the command line, and it would output things like source-space EEG-BOLD correlations, denoised EEG data, etc. we could start using it on simple cases like gradient and bcg denoising and then later extend it to the entire pipeline.

**Comment by gmierz** [comment]
This is setup now, we can run the following as a test:
```
python setup.py install
eegfmripy --list
eegfmripy examplecli
eegfmripy examplecli -c eegfmripy/clianalysis/config_examplecli.yml
```

See https://github.com/russellu/eegfmripy/blob/master/eegfmripy/clianalysis/examplecli.py for an example of how to create a new analysis like `examplecli`.

**Comment by gmierz** [comment]
This is fully implemented and running now for most scripts.
